name: update scripts with file-sync
on:
  workflow_dispatch:
  schedule:
    # At 03:03 on Tuesday
    - cron: '3 3 * * 2'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./.github/sync.sh liulab-dfci/TRUST4 BuildImgtAnnot.pl inst/extdata/TRUST4/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update TRUST4: BuildImgtAnnot.pl"

      - run: ./.github/sync.sh liulab-dfci/TRUST4 BuildDatabaseFa.pl inst/extdata/TRUST4/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update TRUST4: BuildDatabaseFa.pl"

      - run: ./.github/sync.sh sjdlabgroup/SAHMI functions/kreport2mpa.py inst/extdata/kraken2/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update kraken2: kreport2mpa.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools combine_kreports.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: combine_kreports.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools combine_mpa.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: combine_mpa.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools extract_kraken_reads.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: extract_kraken_reads.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools filter_bracken.out.py inst/extdata/KrakenTools/filter_bracken_out.py
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: filter_bracken.out.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools fix_unmapped.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: fix_unmapped.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools kreport2krona.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: kreport2krona.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools kreport2mpa.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: kreport2mpa.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools make_kreport.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: make_kreport.py"

      - run: ./.github/sync.sh jenniferlu717/KrakenTools make_ktaxonomy.py inst/extdata/KrakenTools/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update KrakenTools: make_ktaxonomy.py"
